# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnuxXSo39ZZK6Es2pPipUcY6_0tywC9M
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_excel("agri_dataset_500_samples.xlsx")

df.head()

df = df.groupby("Region").mean(numeric_only=True).reset_index()

df.head()

from google.colab import files

uploaded = files.upload()

import geopandas as gpd
from osgeo import gdal

gdal.SetConfigOption('SHAPE_RESTORE_SHX', 'YES')
gdf = gpd.read_file("geoBoundaries-IND-ADM2.shp")

gdf = gdf.rename(columns={"shapeName": "Region"})
gdf["Region"] = gdf["Region"].str.upper().str.strip()

gdf.head()

gdf = gdf[gdf["Region"].isin(df["Region"])]

print(len(gdf))

geo_df = gdf.merge(df, on="Region")

print("Merged rows:", len(geo_df))

from sklearn.preprocessing import MinMaxScaler

cols = ["Rainfall", "Price", "Cost", "Yield", "Irrigation"]

scaler = MinMaxScaler()
geo_df[cols] = scaler.fit_transform(geo_df[cols])

geo_df["FSI"] = (
    (1 - geo_df["Rainfall"]) +
    (1 - geo_df["Yield"]) +
    (1 - geo_df["Price"]) +
    geo_df["Cost"] -
    geo_df["Irrigation"]
) / 5

geo_df["Stress_Level"] = pd.qcut(
    geo_df["FSI"],
    q=3,
    labels=["Low", "Medium", "High"]
)

import matplotlib.pyplot as plt

geo_df["geometry"] = geo_df["geometry"].simplify(0.05)

geo_df.plot(
    column="Stress_Level",
    cmap="RdYlGn_r",
    legend=True,
    figsize=(6,4)
)

plt.title("Farmer Stress Map (AP & Karnataka)")
plt.show()

pip install streamlit geopandas pandas matplotlib